/**
 * GENERATED by `xanots routes --emit`. Do not edit.
 *
 * Plain data plus one interpolator — this file imports nothing, so a frontend
 * gets the typed path/verb (and socket) contract without pulling the SDK runtime
 * into its bundle. Regenerate after changing an endpoint's name, verb, or api
 * group, or a realtime server's or channel's name.
 */

function fillParams(
  label: string,
  noun: string,
  template: string,
  params?: Record<string, string | number>,
  encode = false,
): string {
  const declared = [...template.matchAll(/\{([^/{}]+)\}/g)].map((m) => m[1]!);
  for (const key of Object.keys(params ?? {})) {
    if (!declared.includes(key)) {
      throw new Error(
        `${label}: \`${key}\` is not a {param} of this ${noun}.` +
          (declared.length ? ` Expected: ${declared.join(", ")}.` : ` This ${noun} is static.`),
      );
    }
  }
  return template.replace(/\{([^/{}]+)\}/g, (_all, key: string) => {
    const value = (params ?? {})[key];
    if (value === undefined || value === null || value === "") {
      throw new Error(`${label}: missing a value for the path param \`${key}\`.`);
    }
    if (typeof value === "number" && !Number.isFinite(value)) {
      throw new Error(`${label}: the path param \`${key}\` is ${value}.`);
    }
    const text = String(value);
    if (text.includes("/")) {
      throw new Error(
        `${label}: the path param \`${key}\` cannot contain "/" — ` +
          `it would address a different ${noun}.`,
      );
    }
    if (!encode) return text;
    // A "." or ".." segment is REMOVED before routing (and takes the segment
    // before it), and encoding does not help — the URL standard reads "%2e" as
    // a dot for that check too. Everything else rides percent-encoded.
    if (/^(\.|%2e){1,2}$/i.test(text)) {
      throw new Error(
        `${label}: the path param \`${key}\` cannot be "${text}" — ` +
          `a "." or ".." segment addresses a different ${noun}.`,
      );
    }
    return encodeURIComponent(text);
  });
}

export const ROUTES = {
  "POST advance": { verb: "POST", path: "/api:ranked/advance" },
  "GET audit": { verb: "GET", path: "/api:ranked/audit" },
  "POST close": { verb: "POST", path: "/api:ranked/close" },
  "POST login": { verb: "POST", path: "/api:ranked/login" },
  "POST override": { verb: "POST", path: "/api:ranked/override" },
  "GET players": { verb: "GET", path: "/api:ranked/players" },
  "GET rank/{player_id}": { verb: "GET", path: "/api:ranked/rank/{player_id}" },
  "POST report": { verb: "POST", path: "/api:ranked/report" },
  "GET seasons": { verb: "GET", path: "/api:ranked/seasons" },
  "POST seed": { verb: "POST", path: "/api:ranked/seed" },
} as const;

/** Every endpoint in this workspace, keyed `"<VERB> <name>"` (e.g. `"GET listings"`). */
export type RouteName = keyof typeof ROUTES;

export function routePath(name: "POST advance"): string;
export function routePath(name: "GET audit"): string;
export function routePath(name: "POST close"): string;
export function routePath(name: "POST login"): string;
export function routePath(name: "POST override"): string;
export function routePath(name: "GET players"): string;
export function routePath(name: "GET rank/{player_id}", params: { "player_id": string | number }): string;
export function routePath(name: "POST report"): string;
export function routePath(name: "GET seasons"): string;
export function routePath(name: "POST seed"): string;

export function routePath(name: RouteName, params?: Record<string, string | number>): string {
  // Read through a widened view: a workspace with no endpoints at all makes
  // `RouteName` `never`, which cannot index the literal type.
  const route = (ROUTES as Record<string, { verb: string; path: string } | undefined>)[name];
  if (!route) {
    throw new Error(
      `routePath: unknown route "${String(name)}". Routes are keyed "<VERB> <name>", ` +
        'e.g. "GET listings" — regenerate the manifest if the endpoint is new.',
    );
  }
  return fillParams(`routePath("${String(name)}")`, "route", route.path, params, true);
}
